# theme: jekyll-theme-modernist
title: One Data Model Registry
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. 
  
# social links
twitter_username:
github_username:

show_excerpts: true # set to false to remove excerpts on the homepage
